name: yolov3-cpu

dependencies:
  - python==3.7
  - pip
  - matplotlib
  - opencv
  - pip:
    - tensorflow==2.0.3
    - lxml
    - tqdm
    - flask
    - seaborn
    - pillow
    - azureml
    - azureml-core
    - azureml-defaults
    - azureml-contrib-services
    - joblib